name = "sandbox-community"
main = "worker.ts"
compatibility_date = "2026-09-01"

[vars]
SITE = "https://sandbox-community.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "sandbox-community"
database_id = "local"

[[r2_buckets]]
binding = "FILES"
bucket_name = "sandbox-community"
